CREATE TABLE chief_table (
  id INT NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(45) NULL,
  LastName VARCHAR(45) NULL,
  BirthDate VARCHAR(45) NULL,
  Gender VARCHAR(45) NULL,
  Address VARCHAR(45) NULL,
  Contact INT NULL,
  FatherFirstName VARCHAR(45) NULL,
  FatherLastName VARCHAR(45) NULL,
  MotherFirstName VARCHAR(45) NULL,
  MotherLastName VARCHAR(45) NULL,
  SssNumber INT NULL,
  Tax VARCHAR(45) NULL,
  Position VARCHAR(45) NULL,
  UnitDivision VARCHAR(45) NULL,
  idNumbers VARCHAR(45) NULL,
  Password VARCHAR(45) NULL,
  ConfirmPassword VARCHAR(45) NULL,
  PRIMARY KEY (id));